version: '3.8'

services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamo-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    networks:
      - zaloedu-net

  redis-local:
    image: "redis:alpine"
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - zaloedu-net

networks:
  zaloedu-net:
    driver: bridge

volumes:
  redis_data:
