import { StyleSheet, Platform } from 'react-native';
import { Colors, Typography } from '../../../constants/Theme';

// Dark theme palette — mirrors the web dark mode colors
const D = {
  bg:            '#0a0e27',
  surface:       '#121621',
  surfaceHigh:   '#1f2438',
  surfaceVar:    '#2a2f42',
  outline:       '#464d5f',
  outlineVar:    '#3a3f52',
  onSurface:     '#e8eef7',
  onSurfaceVar:  '#9ca3b5',
  primary:       '#4a8fff',
  white:         '#ffffff',
  danger:        '#ef4444',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: D.bg,
  },
  header: {
    paddingHorizontal: 12,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#00174d',
  },
  headerBack: {
    fontFamily: 'Material Symbols Outlined',
    fontSize: 26,
    color: D.white,
  },
  headerAvatar: { width: 38, height: 38, borderRadius: 19 },
  headerName: { ...Typography.heading, fontSize: 15, color: D.white },
  headerSub: { ...Typography.body, fontSize: 12, color: 'rgba(255,255,255,0.75)' },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
    paddingRight: 4,
  },
  headerIconButton: {
    padding: 2,
  },
  headerIcon: {
    fontFamily: 'Material Symbols Outlined',
    fontSize: 24,
    color: D.white,
  },
  avatarContainer: { position: 'relative' },
  onlineBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#4cd964',
    borderWidth: 2,
    borderColor: '#00174d',
    zIndex: 11,
  },

  // ── Pin Banner ───────────────────────────────────────────────
  pinBannerContainer: {
    paddingHorizontal: 0,
    backgroundColor: D.surface,
    borderBottomWidth: 1,
    borderBottomColor: D.outlineVar,
    zIndex: 20,
  },
  pinBanner: {
    backgroundColor: D.surface,
  },
  pinBannerMain: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  pinBannerIconBox: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(74,143,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  pinBannerIcon: {
    fontFamily: 'Material Symbols Outlined',
    fontSize: 16,
    color: D.primary,
  },
  pinBannerContent: {
    flex: 1,
    justifyContent: 'center',
  },
  pinBannerLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: D.primary,
    marginBottom: 1,
  },
  pinBannerText: {
    fontSize: 13,
    color: D.onSurface,
  },
  pinBannerCount: {
    fontSize: 13,
    fontWeight: '700',
    color: D.primary,
  },
  pinBannerToggle: {
    padding: 8,
  },
  pinBannerToggleIcon: {
    fontFamily: 'Material Symbols Outlined',
    fontSize: 20,
    color: D.onSurfaceVar,
  },
  pinExpandedList: {
    borderTopWidth: 1,
    borderTopColor: D.outlineVar,
    backgroundColor: D.surface,
    paddingBottom: 4,
  },
  pinExpandedItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: D.bg,
  },
  pinExpandedIdx: {
    fontSize: 11,
    fontWeight: '700',
    color: D.onSurfaceVar,
    width: 20,
  },
  pinExpandedContent: {
    flex: 1,
  },
  pinExpandedText: {
    fontSize: 13,
    color: D.onSurface,
  },
  pinExpandedUnpin: {
    padding: 8,
  },
  pinExpandedUnpinIcon: {
    fontFamily: 'Material Symbols Outlined',
    fontSize: 18,
    color: D.danger,
  },

  listContent: {
    paddingHorizontal: 12,
    paddingTop: 20,
    paddingBottom: 20,
  },

  // ── Action Sheet ─────────────────────────────────────────────
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
    zIndex: 1000,
  },
  actionSheet: {
    backgroundColor: D.surfaceHigh,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === 'ios' ? 40 : 20,
    paddingTop: 16,
  },
  reactionBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 30,
    padding: 8,
    marginBottom: 24,
  },
  reactionEmoji: {
    fontSize: 26,
  },
  reactionPickerEmoji: {
    width: 36,
    height: 36,
    marginHorizontal: 4,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    gap: 16,
    marginBottom: 20,
  },
  actionItem: {
    width: (Platform.OS === 'ios' ? 70 : 80),
    alignItems: 'center',
    gap: 8,
  },
  actionIconBox: {
    width: 50,
    height: 50,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionIcon: {
    fontFamily: 'Material Symbols Outlined',
    fontSize: 24,
  },
  actionText: {
    ...Typography.body,
    fontSize: 12,
    fontWeight: '700',
    color: D.onSurfaceVar,
    textAlign: 'center',
  },
  actionList: {
    borderTopWidth: 1,
    borderTopColor: D.outlineVar,
    paddingTop: 12,
    gap: 4,
  },
  actionListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    gap: 12,
  },
  actionListIcon: {
    fontFamily: 'Material Symbols Outlined',
    fontSize: 22,
    color: D.onSurfaceVar,
  },
  actionListText: {
    ...Typography.body,
    fontSize: 15,
    fontWeight: '600',
    color: D.onSurface,
  },

  // ── Forward Modal ────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
    justifyContent: 'flex-end',
  },
  forwardSheet: {
    backgroundColor: D.surfaceHigh,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '80%',
    paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: D.outlineVar,
  },
  modalTitle: {
    ...Typography.heading,
    fontSize: 18,
    color: D.onSurface,
  },
  closeIcon: {
    fontFamily: 'Material Symbols Outlined',
    fontSize: 24,
    color: D.onSurfaceVar,
  },
  forwardList: {
    padding: 10,
  },
  forwardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    gap: 12,
    borderRadius: 16,
  },
  forwardAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: D.surfaceVar,
  },
  forwardName: {
    flex: 1,
    ...Typography.body,
    fontSize: 15,
    fontWeight: '700',
    color: D.onSurface,
  },
  forwardSendIcon: {
    fontFamily: 'Material Symbols Outlined',
    fontSize: 20,
    color: D.primary,
  },
  forwardCard: {
    backgroundColor: D.surfaceHigh,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '80%',
    paddingBottom: 20,
  },
  forwardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: D.outlineVar,
  },
  forwardTitle: {
    ...Typography.heading,
    fontSize: 16,
    color: D.onSurface,
  },
  forwardClose: {
    fontFamily: 'Material Symbols Outlined',
    fontSize: 24,
    color: D.onSurfaceVar,
  },
  forwardSearch: {
    padding: 12,
  },
  forwardSearchInput: {
    backgroundColor: D.surfaceVar,
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 40,
    ...Typography.body,
    fontSize: 14,
    color: D.onSurface,
  },
  forwardSendBtn: {
    backgroundColor: D.primary,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  forwardSendText: {
    ...Typography.label,
    color: D.white,
    fontSize: 12,
  },

  // ── Scroll to bottom button ──────────────────────────────────
  scrollToBottomBtn: {
    position: 'absolute',
    bottom: 100,
    right: 16,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: D.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
  },
  scrollToBottomIcon: {
    fontFamily: 'Material Symbols Outlined',
    fontSize: 24,
    color: D.white,
  },
  jumpToLatestBadge: {
    position: 'absolute',
    top: -35,
    backgroundColor: D.surface,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: D.outlineVar,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 80,
  },
  jumpToLatestText: {
    fontSize: 11,
    fontWeight: '700',
    color: D.primary,
  },

  // ── Mute modals ──────────────────────────────────────────────
  muteModalCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 16,
    backgroundColor: D.surfaceHigh,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 14,
  },
  muteMenuCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 16,
    backgroundColor: D.surfaceHigh,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
  },
  muteMenuItem: {
    height: 44,
    borderRadius: 10,
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  muteMenuItemText: {
    ...Typography.body,
    fontSize: 14,
    color: D.onSurface,
  },
  muteMenuPrimaryText: {
    ...Typography.label,
    color: D.primary,
  },
  muteMenuDivider: {
    height: 1,
    backgroundColor: D.outlineVar,
    marginVertical: 6,
  },
  muteMenuCancelBtn: {
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: D.surfaceVar,
    marginTop: 2,
  },
  muteMenuCancelText: {
    ...Typography.label,
    fontSize: 12,
    color: D.onSurfaceVar,
  },
  muteModalTitle: {
    ...Typography.heading,
    fontSize: 17,
    color: D.onSurface,
  },
  muteModalSubtitle: {
    ...Typography.body,
    fontSize: 12,
    color: D.onSurfaceVar,
    marginTop: 4,
    marginBottom: 12,
  },
  muteInputsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  muteInputGroup: {
    flex: 1,
  },
  muteInputLabel: {
    ...Typography.label,
    fontSize: 11,
    color: D.onSurfaceVar,
    marginBottom: 6,
  },
  muteTimeInput: {
    height: 40,
    borderWidth: 1,
    borderColor: D.outline,
    borderRadius: 10,
    paddingHorizontal: 10,
    ...Typography.body,
    fontSize: 14,
    color: D.onSurface,
    backgroundColor: D.surfaceVar,
  },
  muteModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 14,
  },
  muteModalCancelBtn: {
    paddingHorizontal: 14,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: D.outline,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: D.surfaceVar,
  },
  muteModalCancelText: {
    ...Typography.label,
    fontSize: 12,
    color: D.onSurfaceVar,
  },
  muteModalApplyBtn: {
    paddingHorizontal: 14,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: D.primary,
  },
  muteModalApplyText: {
    ...Typography.label,
    fontSize: 12,
    color: D.white,
  },
});

export const getStyles = (colors: any, isDark: boolean) => StyleSheet.create({});
