import { StyleSheet, Platform } from 'react-native';
import { Colors, Typography } from '../../../constants/Theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f7f9fb',
  },
  header: {
    paddingHorizontal: 12,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerBack: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 26,
    color: "#fff",
  },
  headerAvatar: { width: 38, height: 38, borderRadius: 19 },
  headerName: { ...Typography.heading, fontSize: 15, color: "#fff" },
  headerSub: { ...Typography.body, fontSize: 12, color: "rgba(255,255,255,0.8)" },
  headerIcons: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
    paddingRight: 4,
  },
  headerIconButton: {
    padding: 2,
  },
  headerIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 24,
    color: "#fff",
  },
  avatarContainer: { position: "relative" },
  onlineBadge: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#4cd964",
    borderWidth: 2,
    borderColor: "#fff",
    zIndex: 11,
  },

  pinStrip: { paddingHorizontal: 10, paddingTop: 8, gap: 6 },
  pinItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e0e6f0",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    gap: 8,
  },
  pinIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 16,
    color: "#0058bc",
  },
  pinText: { flex: 1, ...Typography.body, fontSize: 12, color: "#2f3a4a" },
  pinUnpin: { ...Typography.label, fontSize: 11, color: "#0058bc" },

  listContent: {
    paddingHorizontal: 12,
    paddingTop: 20,
    paddingBottom: 20,
  },

  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
    zIndex: 1000,
  },
  actionSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === 'ios' ? 40 : 20,
    paddingTop: 16,
  },
  reactionBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "rgba(0,0,0,0.03)",
    borderRadius: 30,
    padding: 8,
    marginBottom: 24,
  },
  reactionEmoji: {
    fontSize: 26,
  },
  actionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    gap: 16,
    marginBottom: 20,
  },
  actionItem: {
    width: (Platform.OS === 'ios' ? 70 : 80),
    alignItems: "center",
    gap: 8,
  },
  actionIconBox: {
    width: 50,
    height: 50,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  actionIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 24,
  },
  actionText: {
    ...Typography.body,
    fontSize: 12,
    fontWeight: "700",
    color: "#4b5563",
    textAlign: "center",
  },
  actionList: {
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.05)",
    paddingTop: 12,
    gap: 4,
  },
  actionListItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    gap: 12,
  },
  actionListIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 22,
    color: "#4b5563",
  },
  actionListText: {
    ...Typography.body,
    fontSize: 15,
    fontWeight: "600",
    color: "#1f2937",
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  forwardSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "80%",
    paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.05)",
  },
  modalTitle: {
    ...Typography.heading,
    fontSize: 18,
    color: "#111827",
  },
  closeIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 24,
    color: "#6b7280",
  },
  forwardList: {
    padding: 10,
  },
  forwardItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    gap: 12,
    borderRadius: 16,
  },
  forwardAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#f3f4f6",
  },
  forwardName: {
    flex: 1,
    ...Typography.body,
    fontSize: 15,
    fontWeight: "700",
    color: "#1f2937",
  },
  forwardSendIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 20,
    color: Colors.primary,
  },
  scrollToBottomBtn: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  scrollToBottomIcon: {
    fontFamily: 'Material Symbols Outlined',
    fontSize: 24,
    color: '#fff',
  }
});
