import { StyleSheet } from 'react-native';
import { Colors, Typography } from '../../../constants/Theme';

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#fff" },
  header: {
    paddingHorizontal: 14,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  searchBarWrap: {
    flex: 1,
    height: 38,
    backgroundColor: "rgba(255,255,255,0.18)",
    borderRadius: 19,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    gap: 6,
  },
  headerIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 20,
    color: "rgba(255,255,255,0.8)",
  },
  headerSearchInput: {
    flex: 1,
    ...Typography.body,
    fontSize: 14,
    color: "#fff",
    paddingVertical: 0,
  },
  headerAction: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: "center",
    alignItems: "center",
  },
  headerActionIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 22,
    color: "#fff",
  },

  sectionTabs: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#edf1f7",
    paddingHorizontal: 8,
  },
  sectionTabItem: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  sectionTabActive: { borderBottomColor: "#1f8fff" },
  sectionTabText: {
    ...Typography.label,
    fontSize: 14,
    color: "#5f6f86",
  },
  sectionTabActiveText: { color: "#1f8fff" },

  scroll: { flex: 1 },
  scrollContent: { paddingBottom: 40 },

  toolBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 12,
  },
  toolItem: {
    flex: 1,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#d7dfec",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#fff",
  },
  toolIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 18,
    color: "#5f6f86",
  },
  toolText: { ...Typography.label, fontSize: 13, color: "#5f6f86" },

  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#f7f9fc",
  },
  summaryText: { ...Typography.label, fontSize: 12, color: "#5f6f86" },

  groupHeader: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    backgroundColor: "#e7edf7",
  },
  groupHeaderText: { ...Typography.heading, fontSize: 11, color: "#5f6f86" },

  contactRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderTopWidth: 1,
    borderTopColor: "#edf1f7",
  },
  avatarWrap: { position: "relative" },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#e7edf7",
  },
  statusDot: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 11,
    height: 11,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: "#fff",
    backgroundColor: "#94a3b8",
  },
  onlineDot: { backgroundColor: "#22c55e" },
  contactInfo: { flex: 1, marginLeft: 12 },
  contactName: { ...Typography.heading, fontSize: 15, color: "#1f2733" },
  contactSub: { ...Typography.body, fontSize: 12, color: "#738098", marginTop: 1 },
  contactAction: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  contactActionIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 20,
    color: "#738098",
  },

  center: {
    paddingVertical: 40,
    alignItems: "center",
  },
  emptyText: { ...Typography.body, fontSize: 14, color: "#738098" },

  requestItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "#edf1f7",
  },
  requestAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#e7edf7",
  },
  requestBtnRow: { flexDirection: "row", gap: 6 },
  rejectButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#d7dfec",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  rejectText: { ...Typography.label, fontSize: 11, color: "#5f6f86" },
  acceptButton: {
    borderRadius: 8,
    backgroundColor: "#1f8fff",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  acceptText: { ...Typography.label, fontSize: 11, color: "#fff" },

  suggestItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "#edf1f7",
  },
  skipBtn: {
    borderWidth: 1,
    borderColor: "#d7dfec",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  skipText: { ...Typography.label, fontSize: 11, color: "#5f6f86" },
  addBtn: {
    borderRadius: 8,
    backgroundColor: "#1f8fff",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  addText: { ...Typography.label, fontSize: 11, color: "#fff" },

  groupRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "#edf1f7",
  },
  groupOpenIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 21,
    color: "#1f8fff",
  },

  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingBottom: 20,
    paddingHorizontal: 12,
  },
  sheetItem: {
    borderBottomWidth: 1,
    borderBottomColor: "#edf1f7",
    paddingVertical: 13,
  },
  sheetText: { ...Typography.body, fontSize: 15, color: "#1f2733" },

  nicknameModal: {
    marginHorizontal: 20,
    marginBottom: 90,
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 14,
  },
  nickTitle: { ...Typography.heading, fontSize: 15, color: "#1f2733" },
  nickHint: {
    ...Typography.body,
    fontSize: 12,
    color: "#738098",
    marginTop: 2,
  },
  nickInput: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#d7dfec",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    ...Typography.body,
    color: "#1f2733",
  },
  nickActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
    marginTop: 12,
  },
  cancelBtn: {
    borderWidth: 1,
    borderColor: "#d7dfec",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  cancelText: { ...Typography.label, fontSize: 12, color: "#5f6f86" },
  saveBtn: {
    borderRadius: 8,
    backgroundColor: "#1f8fff",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  disabledBtn: { opacity: 0.55 },
  saveText: { ...Typography.label, fontSize: 12, color: "#fff" },

  profileModal: {
    marginHorizontal: 20,
    marginBottom: 90,
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 14,
    gap: 12,
  },
  profileHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  profileAvatar: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: "#e7edf7",
  },
  profileName: { ...Typography.heading, fontSize: 16, color: "#1f2733" },
  profileEmail: { ...Typography.body, fontSize: 12, color: "#738098" },
  profileLoadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  profileLoadingText: { ...Typography.body, fontSize: 12, color: "#6d7a90" },
  profileInfoWrap: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e3e9f4",
    padding: 10,
    gap: 6,
    backgroundColor: "#fafcff",
  },
  profileInfoRow: {
    ...Typography.body,
    fontSize: 13,
    color: "#2a3340",
  },
  profileActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
});
