import { StyleSheet } from 'react-native';
import { Colors, Typography } from '../../../constants/Theme';

export const getContactsStyles = (colors: any) => StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.surface },
  header: {
    paddingHorizontal: 14,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  searchBarWrap: {
    flex: 1,
    height: 38,
    backgroundColor: colors.surfaceVariant,
    borderRadius: 19,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    gap: 6,
  },
  headerIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 20,
    color: colors.onPrimary,
  },
  headerSearchInput: {
    flex: 1,
    ...Typography.body,
    fontSize: 14,
    color: colors.surface,
    paddingVertical: 0,
  },
  headerAction: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: "center",
    alignItems: "center",
  },
  headerActionIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 22,
    color: colors.surface,
  },

  sectionTabs: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: colors.outlineVariant,
    paddingHorizontal: 8,
  },
  sectionTabItem: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  sectionTabActive: { borderBottomColor: "#1f8fff" },
  sectionTabText: {
    ...Typography.label,
    fontSize: 14,
    color: colors.onSurfaceVariant,
  },
  sectionTabActiveText: { color: "#1f8fff" },

  scroll: { flex: 1 },
  scrollContent: { paddingBottom: 40 },

  toolBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 12,
  },
  toolItem: {
    flex: 1,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: colors.surface,
  },
  toolIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 18,
    color: colors.onSurfaceVariant,
  },
  toolText: { ...Typography.label, fontSize: 13, color: colors.onSurfaceVariant },

  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: colors.surfaceContainer,
  },
  summaryText: { ...Typography.label, fontSize: 12, color: colors.onSurfaceVariant },

  groupHeader: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    backgroundColor: colors.surfaceContainerHigh,
  },
  groupHeaderText: { ...Typography.heading, fontSize: 11, color: colors.onSurfaceVariant },

  contactRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderTopWidth: 1,
    borderTopColor: colors.outlineVariant,
  },
  avatarWrap: { position: "relative" },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.surfaceContainerHigh,
  },
  statusDot: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 11,
    height: 11,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: colors.surface,
    backgroundColor: colors.outline,
  },
  onlineDot: { backgroundColor: "#22c55e" },
  contactInfo: { flex: 1, marginLeft: 12 },
  contactName: { ...Typography.heading, fontSize: 15, color: colors.onSurface },
  contactSub: { ...Typography.body, fontSize: 12, color: colors.onSurfaceVariant, marginTop: 1 },
  contactAction: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  contactActionIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 20,
    color: colors.onSurfaceVariant,
  },

  center: {
    paddingVertical: 40,
    alignItems: "center",
  },
  emptyText: { ...Typography.body, fontSize: 14, color: colors.onSurfaceVariant },

  requestItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: colors.outlineVariant,
  },
  requestAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.surfaceContainerHigh,
  },
  requestBtnRow: { flexDirection: "row", gap: 6 },
  rejectButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  rejectText: { ...Typography.label, fontSize: 11, color: colors.onSurfaceVariant },
  acceptButton: {
    borderRadius: 8,
    backgroundColor: "#1f8fff",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  acceptText: { ...Typography.label, fontSize: 11, color: colors.surface },

  suggestItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: colors.outlineVariant,
  },
  skipBtn: {
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  skipText: { ...Typography.label, fontSize: 11, color: colors.onSurfaceVariant },
  addBtn: {
    borderRadius: 8,
    backgroundColor: "#1f8fff",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  addText: { ...Typography.label, fontSize: 11, color: colors.surface },

  groupRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: colors.outlineVariant,
  },
  groupOpenIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 21,
    color: "#1f8fff",
  },

  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingBottom: 20,
    paddingHorizontal: 12,
  },
  sheetItem: {
    borderBottomWidth: 1,
    borderBottomColor: colors.outlineVariant,
    paddingVertical: 13,
  },
  sheetText: { ...Typography.body, fontSize: 15, color: colors.onSurface },

  nicknameModal: {
    marginHorizontal: 20,
    marginBottom: 90,
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 14,
  },
  nickTitle: { ...Typography.heading, fontSize: 15, color: colors.onSurface },
  nickHint: {
    ...Typography.body,
    fontSize: 12,
    color: colors.onSurfaceVariant,
    marginTop: 2,
  },
  nickInput: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    ...Typography.body,
    color: colors.onSurface,
  },
  nickActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
    marginTop: 12,
  },
  cancelBtn: {
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  cancelText: { ...Typography.label, fontSize: 12, color: colors.onSurfaceVariant },
  saveBtn: {
    borderRadius: 8,
    backgroundColor: "#1f8fff",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  disabledBtn: { opacity: 0.55 },
  saveText: { ...Typography.label, fontSize: 12, color: colors.surface },

  profileModal: {
    marginHorizontal: 20,
    marginBottom: 90,
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 14,
    gap: 12,
  },
  profileHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  profileAvatar: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: colors.surfaceContainerHigh,
  },
  profileName: { ...Typography.heading, fontSize: 16, color: colors.onSurface },
  profileEmail: { ...Typography.body, fontSize: 12, color: colors.onSurfaceVariant },
  profileLoadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  profileLoadingText: { ...Typography.body, fontSize: 12, color: colors.onSurfaceVariant },
  profileInfoWrap: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    padding: 10,
    gap: 6,
    backgroundColor: colors.surfaceContainerLowest,
  },
  profileInfoRow: {
    ...Typography.body,
    fontSize: 13,
    color: colors.onSurface,
  },
  profileActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
  },
});
