import { StyleSheet, Platform } from "react-native";
import { Colors, Typography } from "../../../constants/Theme";

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#f7f9fb" },
  keyboardAvoidingContainer: { flex: 1 },
  header: { paddingBottom: 14, paddingHorizontal: 16 },
  headerContent: { flexDirection: "row", alignItems: "center", gap: 8 },
  searchContainer: {
    flex: 1,
    height: 38,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
  },
  searchIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 20,
    color: "#fff",
    marginRight: 8,
  },
  searchInput: { flex: 1, color: "#fff", ...Typography.body, fontSize: 15 },
  iconButton: { padding: 4 },
  headerIconText: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 24,
    color: "#fff",
  },
  headerIcons: {
    flexDirection: "row",
    alignItems: "center",
  },
  notificationBadge: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 10,
    height: 10,
    backgroundColor: "#ff3b30",
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: "#0058bc",
    zIndex: 1,
  },

  content: { flex: 1, paddingBottom: 92 },
  scrollContainer: { flex: 1 },

  sectionHeader: { padding: 16, paddingBottom: 8 },
  sectionTitle: { ...Typography.heading, fontSize: 18, color: "#00418f" },

  chatList: { paddingBottom: 110 },
  chatItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    backgroundColor: "#fff",
    borderBottomWidth: Platform.OS === "android" ? 1 : 0.5,
    borderBottomColor: "#eceef0",
  },
  avatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    marginRight: 14,
    backgroundColor: "#e0e3e5",
  },
  avatarContainer: { position: "relative" },
  unreadBadge: {
    position: "absolute",
    right: -4,
    top: -4,
    backgroundColor: "#ff3b30", // Vibrant iOS red
    borderRadius: 12,
    minWidth: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: "#fff",
    zIndex: 10,
  },
  onlineBadge: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#4cd964", // Vibrant Green
    borderWidth: 2,
    borderColor: "#fff",
    zIndex: 11,
  },
  unreadBadgeText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "900",
  },
  chatInfo: { flex: 1 },
  chatHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 2,
  },
  chatName: {
    ...Typography.heading,
    fontSize: 15,
    color: "#191c1e",
    flex: 1,
    marginRight: 8,
  },
  chatTime: { ...Typography.body, fontSize: 12, color: "#727784" },
  lastMsg: { ...Typography.body, fontSize: 13, color: "#727784" },

  chatPane: { flex: 1, backgroundColor: "#f7f9fb" },
  chatPaneHeader: {
    paddingHorizontal: 12,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  chatPaneBack: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 26,
    color: "#fff",
  },
  chatPaneAvatar: { width: 38, height: 38, borderRadius: 19 },
  chatPaneName: { ...Typography.heading, fontSize: 15, color: "#fff" },
  chatPaneSub: { ...Typography.body, fontSize: 12, color: "rgba(255,255,255,0.8)" },
  chatHeaderIcons: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
    paddingRight: 4,
  },
  chatHeaderIconButton: {
    padding: 2,
  },
  chatHeaderIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 24,
    color: "#fff",
  },

  pinStrip: { paddingHorizontal: 10, paddingTop: 8, gap: 6 },
  pinItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e0e6f0",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    gap: 8,
  },
  pinIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 16,
    color: "#0058bc",
  },
  pinText: { flex: 1, ...Typography.body, fontSize: 12, color: "#2f3a4a" },
  pinUnpin: { ...Typography.label, fontSize: 11, color: "#0058bc" },

  messagesContainer: { flex: 1 },
  messageRow: { flexDirection: "row", alignItems: "flex-end", gap: 8 },
  messageRowMe: { justifyContent: "flex-end" },
  messageRowOther: { justifyContent: "flex-start" },
  msgAvatar: { width: 28, height: 28, borderRadius: 14 },
  messageBubble: {
    maxWidth: "78%",
    borderRadius: 16,
    padding: 10,
    borderWidth: 1,
  },
  messageBubbleMe: { backgroundColor: "#dfefff", borderColor: "#c8dcff" },
  messageBubbleOther: { backgroundColor: "#fff", borderColor: "#e3e8f0" },
  messageText: { ...Typography.body, fontSize: 14, color: "#1f2631" },
  recalledText: { fontStyle: "italic", opacity: 0.72 },
  replyBlock: {
    backgroundColor: "rgba(255,255,255,0.6)",
    borderWidth: 1,
    borderColor: "#d9e1f0",
    borderRadius: 8,
    padding: 6,
    marginBottom: 6,
  },
  replySender: { ...Typography.label, fontSize: 11, color: "#0058bc" },
  replyContent: { ...Typography.body, fontSize: 12, color: "#5f6570" },
  messageImage: {
    width: 190,
    height: 190,
    borderRadius: 10,
    backgroundColor: "#e8edf5",
  },
  messageFile: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#dfe5ef",
    borderRadius: 10,
    padding: 8,
  },
  messageFileIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 20,
    color: "#51617a",
  },
  messageFileName: { ...Typography.label, fontSize: 12, color: "#1f2631" },
  messageFileSize: { ...Typography.body, fontSize: 11, color: "#7a8391" },

  replyComposer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: "#e5eaf2",
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#fff",
  },
  replyComposerTitle: { ...Typography.label, fontSize: 12, color: "#0058bc" },
  replyComposerText: { ...Typography.body, fontSize: 12, color: "#6e7683" },
  replyComposerCancel: {
    ...Typography.heading,
    fontSize: 16,
    color: "#6e7683",
  },

  attachmentStrip: { maxHeight: 56, backgroundColor: "#fff" },
  attachmentChip: {
    height: 34,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    backgroundColor: "#f4f7fb",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#dfe5ef",
  },
  attachmentIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 16,
    color: "#5b6b84",
  },
  attachmentName: {
    ...Typography.body,
    fontSize: 12,
    maxWidth: 150,
    color: "#2f3a4a",
  },
  attachmentRemove: { ...Typography.heading, fontSize: 12, color: "#677389" },

  composer: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#e5eaf2",
    paddingHorizontal: 10,
    paddingVertical: 8,
    paddingBottom: Platform.OS === "ios" ? 14 : 8,
  },
  composerAction: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f1f5fa",
  },
  composerActionIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 20,
    color: "#52627f",
  },
  composerInput: {
    flex: 1,
    maxHeight: 110,
    minHeight: 40,
    borderWidth: 1,
    borderColor: "#dfe5ef",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 8,
    ...Typography.body,
    fontSize: 14,
    color: "#1f2631",
    backgroundColor: "#fff",
  },
  sendButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0058bc",
  },
  sendButtonText: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 20,
    color: "#fff",
  },

  friendItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    backgroundColor: "#fff",
    borderBottomWidth: Platform.OS === "android" ? 1 : 0.5,
    borderBottomColor: "#eceef0",
  },
  friendAvatar: { width: 48, height: 48, borderRadius: 24, marginRight: 16 },
  friendInfo: { flex: 1 },
  friendName: { ...Typography.heading, fontSize: 16, color: "#191c1e" },
  friendStatus: { ...Typography.body, fontSize: 12, color: "#727784" },
  friendAction: { padding: 8 },
  friendActionIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 24,
    color: "#00418f",
  },

  searchResultCard: {
    marginHorizontal: 16,
    marginBottom: 10,
    padding: 12,
    backgroundColor: "#fff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e0e6f0",
  },
  searchResultHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  searchResultAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    marginRight: 10,
    backgroundColor: "#e8edf5",
  },
  searchResultName: { ...Typography.heading, fontSize: 15, color: "#1f2631" },
  searchResultEmail: { ...Typography.body, fontSize: 12, color: "#6d7685" },
  searchResultHint: { ...Typography.body, fontSize: 12, color: "#5f697a" },
  searchResultPrimaryButton: {
    backgroundColor: "#0058bc",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 9,
  },
  searchResultPrimaryText: { ...Typography.label, fontSize: 13, color: "#fff" },

  pendingSection: {
    marginHorizontal: 16,
    marginBottom: 12,
    backgroundColor: "#fff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e0e6f0",
    overflow: "hidden",
  },
  pendingSectionTitle: {
    ...Typography.heading,
    fontSize: 14,
    color: "#1f2631",
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 4,
  },
  pendingItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: "#edf1f7",
  },
  pendingName: { ...Typography.heading, fontSize: 14, color: "#1f2631" },
  pendingEmail: { ...Typography.body, fontSize: 11, color: "#6d7685" },
  pendingAcceptButton: {
    backgroundColor: "#0058bc",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  pendingAcceptText: { ...Typography.label, fontSize: 12, color: "#fff" },

  centeredView: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  aiIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 80,
    color: "#00418f",
    marginBottom: 20,
    opacity: 0.8,
  },
  aiTitle: {
    ...Typography.heading,
    fontSize: 24,
    color: "#191c1e",
    marginBottom: 8,
  },
  aiSubtitle: {
    ...Typography.body,
    fontSize: 16,
    color: "#727784",
    textAlign: "center",
  },

  profileHeader: {
    alignItems: "center",
    padding: 32,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#eceef0",
  },
  largeAvatarBox: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#0058bc",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  largeAvatarImage: { width: 100, height: 100, borderRadius: 50 },
  profileName: {
    ...Typography.heading,
    fontSize: 22,
    color: "#191c1e",
    marginBottom: 4,
  },
  profileEmail: { ...Typography.body, fontSize: 14, color: "#727784" },
  menuContainer: { padding: 16, paddingTop: 24 },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    backgroundColor: "#fff",
    borderRadius: 16,
    marginBottom: 12,
  },
  menuIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  menuIcon: { fontFamily: "Material Symbols Outlined", fontSize: 22 },
  menuLabel: { flex: 1, ...Typography.heading, fontSize: 16, color: "#191c1e" },
  menuArrow: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 20,
    color: "#c2c6d5",
  },
  divider: {
    height: 1,
    backgroundColor: "#eceef0",
    marginVertical: 12,
    marginHorizontal: 8,
  },

  fileHistoryItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#edf1f6",
  },
  fileHistoryIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 20,
    color: "#5a6781",
  },
  fileHistoryName: { ...Typography.label, fontSize: 13, color: "#1f2631" },
  fileHistoryMeta: { ...Typography.body, fontSize: 11, color: "#7a8391" },

  floatingTabBar: {
    position: "absolute",
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.05)",
    ...Platform.select({
      ios: {
        bottom: 0,
        left: 0,
        right: 0,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
      },
      android: {
        bottom: 16,
        left: 20,
        right: 20,
        height: 64,
        borderRadius: 32,
        elevation: 12,
        borderWidth: 1,
        borderColor: "rgba(0,0,0,0.05)",
      },
    }),
  },
  tabItem: { flex: 1, alignItems: "center", justifyContent: "center" },
  tabIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 24,
    color: "#727784",
    marginBottom: 4,
  },
  tabIconActive: { color: "#00418f", fontVariationSettings: "'FILL' 1" },
  tabLabel: { ...Typography.label, fontSize: 10, color: "#727784" },
  tabLabelActive: { color: "#00418f" },

  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
    zIndex: 1000,
  },
  actionSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingBottom: 40,
    paddingTop: 16,
  },
  reactionBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "rgba(0,0,0,0.03)",
    borderRadius: 30,
    padding: 8,
    marginBottom: 24,
  },
  reactionOption: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
  },
  reactionEmoji: {
    fontSize: 26,
  },
  actionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    gap: 16,
    marginBottom: 20,
  },
  actionItem: {
    width: (Platform.OS === 'ios' ? 70 : 80),
    alignItems: "center",
    gap: 8,
  },
  actionIconBox: {
    width: 50,
    height: 50,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  actionIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 24,
  },
  actionText: {
    ...Typography.body,
    fontSize: 12,
    fontWeight: "700",
    color: "#4b5563",
    textAlign: "center",
  },
  actionList: {
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.05)",
    paddingTop: 12,
    gap: 4,
  },
  actionListItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    gap: 12,
  },
  actionListIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 22,
    color: "#4b5563",
  },
  actionListText: {
    ...Typography.body,
    fontSize: 15,
    fontWeight: "600",
    color: "#1f2937",
  },

  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  forwardSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "80%",
    paddingBottom: 40,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.05)",
  },
  modalTitle: {
    ...Typography.heading,
    fontSize: 18,
    color: "#111827",
  },
  closeIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 24,
    color: "#6b7280",
  },
  forwardList: {
    padding: 10,
  },
  forwardItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    gap: 12,
    borderRadius: 16,
  },
  forwardAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#f3f4f6",
  },
  forwardName: {
    flex: 1,
    ...Typography.body,
    fontSize: 15,
    fontWeight: "700",
    color: "#1f2937",
  },
  forwardSendIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 20,
    color: Colors.primary,
  },

  // QR Scanner Styles
  scannerOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  scannerHeader: {
    height: 60,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
  },
  scannerCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  scannerCloseIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 24,
    color: "#fff",
  },
  scannerTitle: {
    ...Typography.heading,
    fontSize: 18,
    color: "#fff",
  },
  scannerFrameContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 100,
  },
  scannerFrame: {
    width: 250,
    height: 250,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.3)",
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.05)",
    overflow: "hidden",
  },
  scannerCorner: {
    position: "absolute",
    width: 24,
    height: 24,
    borderColor: "#fff",
    borderWidth: 4,
  },
  topLeft: {
    top: -2,
    left: -2,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderTopLeftRadius: 12,
  },
  topRight: {
    top: -2,
    right: -2,
    borderLeftWidth: 0,
    borderBottomWidth: 0,
    borderTopRightRadius: 12,
  },
  bottomLeft: {
    bottom: -2,
    left: -2,
    borderRightWidth: 0,
    borderTopWidth: 0,
    borderBottomLeftRadius: 12,
  },
  bottomRight: {
    bottom: -2,
    right: -2,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderBottomRightRadius: 12,
  },
  scanLine: {
    width: "100%",
    height: 2,
    backgroundColor: Colors.primary,
    position: "absolute",
    top: "50%",
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 10,
  },

  // Add Menu (+) Styles
  addMenuOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.1)", // Very light tint
  },
  addMenuDropdown: {
    position: "absolute",
    right: 12,
    width: 200,
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingVertical: 8,
    // Premium Shadow
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 8,
  },
  addMenuArrow: {
    position: "absolute",
    top: -6,
    right: 12,
    width: 12,
    height: 12,
    backgroundColor: "#fff",
    transform: [{ rotate: "45deg" }],
  },
  addMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 12,
  },
  addMenuIcon: {
    fontFamily: "Material Symbols Outlined",
    fontSize: 22,
    color: "#5a6781",
  },
  addMenuLabel: {
    ...Typography.body,
    fontSize: 15,
    color: "#1f2631",
    fontWeight: "500",
  },
  addMenuDivider: {
    height: 1,
    backgroundColor: "#f1f3f5",
    marginVertical: 4,
  },
});
